from typing import Dict, List, Tuple

class PIIDetectorAgent:
    """
    Inspects schemas provided by DataHub Context and identifies sensitive fields.
    """
    PII_KEYWORDS = ["email", "ssn", "password", "credit_card", "phone", "tax_id"]

    def inspect_schema(self, columns: List[Dict[str, str]]) -> Tuple[List[str], List[str]]:
        detected_fields = []
        for col in columns:
            name = col.get("name", "").lower()
            if any(keyword in name for keyword in self.PII_KEYWORDS):
                detected_fields.append(col["name"])
        
        tags = ["PII-Sensitive", "GDPR-Restricted"] if detected_fields else []
        return detected_fields, tags

    def generate_dbt_masking_model(self, table_name: str, pii_columns: List[str]) -> str:
        select_statements = []
        for col in pii_columns:
            if "email" in col.lower():
                select_statements.append(f"    SHA256({col}) AS {col}_hashed")
            elif "phone" in col.lower() or "ssn" in col.lower():
                select_statements.append(f"    CONCAT('***-**-', RIGHT({col}, 4)) AS {col}_masked")
            else:
                select_statements.append(f"    MD5({col}) AS {col}_anonymized")

        sql_body = ",\n".join(select_statements)
        
        return f"""-- Auto-generated by DataGuard Agent via DataHub Metadata Context
-- Target Table: {table_name}
-- Identified PII Fields: {', '.join(pii_columns)}

SELECT
    id,
    created_at,
{sql_body}
FROM {{{{ source('raw_data', '{table_name}') }}}}
"""
