-- Auto-generated by DataGuard Agent via DataHub Metadata Context
-- Target Table: users
-- Identified PII Fields: user_email, phone_number

SELECT
    id,
    created_at,
    SHA256(user_email) AS user_email_hashed,
    CONCAT('***-**-', RIGHT(phone_number, 4)) AS phone_number_masked
FROM {{ source('raw_data', 'users') }}
